{"name": "登录测试：正确账号密码登录", "status": "broken", "statusDetails": {"message": "TypeError: argument of type 'NoneType' is not iterable", "trace": "self = <test_send_code.TestAuthLogin object at 0x000001E91FB82AD0>\nreq_session = <requests.sessions.Session object at 0x000001E91FB8FB50>, phone = '13350180915', password = '123456'\nlogin_type = 2, expect_success = True, expect_errorCode = None, scene_desc = '正确账号密码登录'\n\n    @allure.story(\"登录场景（参数化批量测试：正常+失败）\")\n    @allure.title(\"登录测试：{scene_desc}\")\n    @pytest.mark.parametrize(\"phone, password, login_type, expect_success, expect_errorCode, scene_desc\", login_param_data)\n    def test_login_parametrize(self, req_session, phone, password, login_type, expect_success, expect_errorCode, scene_desc):\n        \"\"\"参数化测试：覆盖登录的正常场景+5种失败场景\"\"\"\n        # 1. 接口信息\n        login_url = f\"{BASE_URL}{LOGIN_URL}\"\n        login_payload = {\n            \"phone\": phone,\n            \"password\": password,\n            \"type\": login_type\n        }\n    \n        # 2. 发送请求\n        with allure.step(f\"发送登录请求：{scene_desc}\"):\n            response = req_session.post(url=login_url, json=login_payload)\n            print(f\"\\n【{scene_desc}】登录响应: {response.text}\")\n    \n        # 3. 断言\n        with allure.step(\"验证HTTP状态码为200\"):\n            assert response.status_code == 200, f\"登录请求异常：状态码{response.status_code}\"\n    \n        login_result = response.json()\n        with allure.step(f\"验证success标识：预期{expect_success}\"):\n            assert login_result.get(\"success\") is expect_success, \\\n                f\"登录结果异常：预期{expect_success}，实际{login_result.get('success')}\"\n    \n        with allure.step(f\"验证提示信息：包含「{expect_errorCode}」\"):\n            actual_errorCode = login_result.get(\"errorCode\", \"\")\n>           assert expect_errorCode in actual_errorCode, \\\n                f\"提示信息异常：预期包含「{expect_errorCode}」，实际「{actual_errorCode}」\"\nE           TypeError: argument of type 'NoneType' is not iterable\n\ntest_send_code.py:157: TypeError"}, "description": "参数化测试：覆盖登录的正常场景+5种失败场景", "steps": [{"name": "发送登录请求：正确账号密码登录", "status": "passed", "start": 1757472939207, "stop": 1757472939464}, {"name": "验证HTTP状态码为200", "status": "passed", "start": 1757472939464, "stop": 1757472939464}, {"name": "验证success标识：预期True", "status": "passed", "start": 1757472939464, "stop": 1757472939464}, {"name": "验证提示信息：包含「None」", "status": "broken", "statusDetails": {"message": "TypeError: argument of type 'NoneType' is not iterable\n", "trace": "  File \"C:\\Users\\33042\\Desktop\\api_test_project\\test_send_code.py\", line 157, in test_login_parametrize\n    assert expect_errorCode in actual_errorCode, \\\n"}, "start": 1757472939464, "stop": 1757472939464}], "attachments": [{"name": "stdout", "source": "15a11687-c06c-4063-a768-96753fda70f5-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "phone", "value": "'13350180915'"}, {"name": "password", "value": "'123456'"}, {"name": "login_type", "value": "2"}, {"name": "expect_success", "value": "True"}, {"name": "expect_errorCode", "value": "None"}, {"name": "scene_desc", "value": "'正确账号密码登录'"}], "start": 1757472939207, "stop": 1757472939464, "uuid": "46dc4480-1d9c-4931-9cb3-c2324c2a4fd2", "historyId": "b1de588179645bb21e87a92cf6fd1c1b", "testCaseId": "2701f847e7f19ec0661f20edaaf0e9ac", "fullName": "test_send_code.TestAuthLogin#test_login_parametrize", "labels": [{"name": "feature", "value": "2. 用户登录接口"}, {"name": "story", "value": "登录场景（参数化批量测试：正常+失败）"}, {"name": "suite", "value": "test_send_code"}, {"name": "subSuite", "value": "TestAuthLogin"}, {"name": "host", "value": "2001TXY-HP"}, {"name": "thread", "value": "35256-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_send_code"}], "titlePath": ["test_send_code.py", "TestAuthLogin"]}